[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
showErrorDetails = false
showSidebarNavigation = false

[theme]
base = "light"
primaryColor = "#1a3a5c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f6fa"
textColor = "#1a3a5c"
font = "sans serif"
